name: polymath
favicon: null
layout_spectrum: 0.3770227604545653
typography_spectrum: 0.6008782347198576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8953725351020694
  lightness: 0.6951287284027785
  saturation: 0.1541928027290851
  rhythmicContrast: 0.23808596096932888
purpose: []
